# 打开https://tieba.baidu.com/index.html 查看源代码搜索  {"user_id": 获取
UID: 352886927
# 度盘的cookie信息 退出登录会导致bduss过期 如需换号就清空cookie吧
BDUSS: 'I0RTRpWUZNTzNQdUM3TU9NR29jelB6b295c2dwOVVZcHVrRVF1ZXd2VjFxRUJnRVFBQUFBJCQAAAAAAAAAAAEAAACPoAgVMTA1NzA2OTY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHUbGWB1GxlgNl'
STOKEN: 'f1ebc15972472ee7120c89c2276c7563359fddd26aae96443db4a8771e083064'
BAIDUID: 'C46354F7CD91A19B474295795ED317B6:FG=1'


comm:
  # 触发的命令
  keyword:
    - pan#
    - p#
    - 'https?://pan.baidu.com/'

  # 获取链接秒传信息
  get_ru:
    - pru#
    - ru#

  # 获取直链和秒传信息
  get_all:
    - pall#
    - pl#


  # 提取码或目录的分隔符
  split: ' '
  # 帮助命令
  help: panhelp

  link2bdlink: p2#

rules:
  # 秒传存放目录 位于度盘里
  dulink_temp_dir: 'temp/'
  # 签名缓存时间 单位小时
  sign_cache_time: 1

  # 以下设置为使用秒传链接下载时 中转保存至网盘中后分享下载的设置
  #是否自动取消分享
  auto_cancel_share: true
  # 设定n小时后取消
  auto_cancel_share_time: 8
  # 取消分享后删除文件
  delete_share_file: true

str:
  help:
    - |
      [https://pan.baidu.com/s/xxx#提取码] 获取一个下载地址
      [p#分享地址 提取码] 获取一个下载地址
      [p#秒传链接] 获取一个下载地址
      [ru#分享地址 提取码] 生成一个秒传地址
      [pl#分享地址 提取码] 获取下载地址和秒传地址
      支持秒传(PanDL/梦姬/游侠/PCS-Go)链接
    - |
      因百度限制，需修改浏览器UA后下载。
      下列设置后填入以下UA
      LogStatistic

      xdown（推荐）
      设置 -> User-Agent -> 填入 LogStatistic
      复制链接，新建任务直接下载即可

      IDM（推荐）
      选项 -> 下载 -> 手动添加任务时使用的用户代理（UA）-> 填入 LogStatistic
      右键复制下载链接，在 IDM 新建任务，粘贴链接即可下载。

      ADM Pro（Android推荐）
      设置 –> 下载中 –> 浏览器标识 –> 自定义 浏览器标识
      填入： LogStatistic
      切换到浏览器（ADM留在后台），长按“下载链接”，选择复制链接地址
      然后在ADM这里点击开始即可

      Chrome浏览器
      安装浏览器扩展程序 User-Agent Switcher for Chrome
      https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg
      右键点击扩展图标 -> 选项
      New User-agent name 填入 百度网盘分享下载
      New User-Agent String 填入 LogStatistic
      Group 填入 百度网盘
      Append? 选择 Replace
      Indicator Flag 填入 Log，点击 Add 保存
      保存后点击扩展图标，出现"百度网盘"，进入并选择"百度网盘分享下载"。

      Pure浏览器（Android）
      设置 –> 浏览设置 -> 浏览器标识(UA)
      添加自定义UA：LogStatistic

      Alook浏览器（IOS）
      设置 -> 通用设置 -> 浏览器标识 -> 移动版浏览器标识 -> 自定义 ->
      填入 LogStatistic

      关于秒传链接的使用
      浏览器安装Tampermonkey插件
      脚本地址:
      https://greasyfork.org/en/scripts/397324-%25E7%25A7%2592%25E4%25BC%25A0%25E9%2593%25BE%25E6%258E%25A5%25E6%258F%2590%25E5%258F%2596